# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 18a51ab9f5e984dd770080cf42c80711cf8b4d6569ad3b038ac08bda921c73b951a72459df4e7074eb916000b7319b25ab41b5b01200ef674d8f4d3c93c42a3e

test:
  secret_key_base: 5a96cf0864d72a931b0120aba4739d2f0ac5786740d0d3f6f1912a669d3e9f94f225fb55fd108df2815dbc012c5cb42af6e39440fdc47cbb37389ddaed05e19e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
